spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tabor_website
    username: admin
    password: admin
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
server:
  port: 8080