CREATE TABLE nails_for_sale
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    style       VARCHAR(255),
    theme       VARCHAR(255),
    color       VARCHAR(255),
    size        VARCHAR(255),
    price_cents INTEGER                                 NOT NULL,
    qty         INTEGER                                 NOT NULL,
    CONSTRAINT pk_nails_for_sale PRIMARY KEY (id)
);